### ISSUE TITLE
用开发环境启动后无法获取代理信息

### ISSUE THREAD

**Issue by jason1235** [1again/ProxyPool#1]
提示{"message": "Internal Server Error"}
docker安装了 用的宝塔面板自带的

顺便问一下 Config.ini.default 是不是需要把default去掉，去掉后放在哪个文件夹里面？

**Comment by ozhiwei** [comment]
抱歉， 目前正在重构和添加一些新功能，所以没有release的版本。

根据你的错误提示没法判断是什么问题， 你能够提供更多信息来，比如`docker logs`

`Config.ini.default` 是默认的配置文件， 如果你没有定制化的需求是不用进行修改的。
如果你想进行定制化， 所以`copy`一份改成`Config.ini`文件，不要对原文件进行修改。

另外, 我看你启动的是开发环境, 就说明你是有一定技术水平的, 弱弱的问一下
你启动了mongodb了吗, 开发模式下要自己搭建mongodb的

如果你只是使用的, 直接用生产环境!
