### ISSUE TITLE
ProxyFetchSchedule 不工作

### ISSUE THREAD

**Issue by 1gendajiba** [1again/ProxyPool#10]
部署完成后只有第一次抓取了代理，之后只会对已采集的代理进行验证而不会采集新代理

**Comment by ozhiwei** [comment]
打开`http://your_host:35050/admin/fetchermodel/`
看下`Next Fetch Time`字段的时间对吗? 应该在半个小时之内.

**Comment by 1gendajiba** [comment]
我用centos7.2部署的docker，都是默认的参数，Interval 30分钟，Next Fetch Time到时间后不抓取新代理，时间也不会更新，跟你的demo一样的http://proxy.1again.cc:35050/admin/fetchermodel/，一直停留在第一次安装抓取后的30分钟。

**Comment by ozhiwei** [comment]
恭喜你, 发现了一个bug.
已经被我给修理了, 直接更新`docker pull 1again/proxy_pool`
感谢你的反馈.
