### ISSUE TITLE
支持动态代理(手动加粗)

### ISSUE THREAD

**Issue by jasonlee529** [1again/ProxyPool#13]
我自己用docker启动的proxypool ，为啥不能通过动态代理呢？暴露的端口不对吗？

`docker run -d --name mongo -v /data/mongodb:/data -p 27017:27017 mongo`

`docker run -d --name proxy_pool --link mongo:proxy_pool_db -p 35050:35050 1again/proxy_pool`
命令如下：
```
# curl -x "ip:35050" https://httpbin.org/ip
curl: (56) Received HTTP code 404 from proxy after CONNECT

# curl -x "proxy.1again.cc:36050" https://httpbin.org/ip
{
  "origin": "221.4.150.7, 221.4.150.7"
}
```

**Comment by ozhiwei** [comment]
是的, 动态代理的端口是`36050`
不管光抄啊, 好歹改改名字啊!

**Comment by jasonlee529** [comment]
那就是把36050端口映射出来就可以直接用动态代理了吧？动态代理分配ip有什么策略吗？

**Comment by ozhiwei** [comment]
1. 映射出来就可以使用了.
2. 每个域名, 请求时依次使用`可用率最高`和`最后验证成功`的代理, 不停的重复.

**Comment by jasonlee529** [comment]
谢谢解答
