### ISSUE TITLE
cannot fetch new proxy periodically

### ISSUE THREAD

**Issue by WeiliangXing** [1again/ProxyPool#14]
即使缩短fetch_new_proxy_interval值 在mongodb上proxy 在interval 之后 仍不变。 如何能周期性获取新proxy？

**Comment by ozhiwei** [comment]
确定你的1again/proxy_pool image是最新的吗?
之前确实有这个bug, 但已经修复了.
你可以在linux下执行`docker pull 1again/proxy_pool`来确保你的image是最新的.
