### ISSUE TITLE
采集了好几天没有数据

### ISSUE THREAD

**Issue by ciweiin** [1again/ProxyPool#2]
[{"result":"not found"},{"status_code":404},{"github":"https://github.com/1again/ProxyPool"},{"api_list":{"/v1/proxies/":{"args":{"https":{"desc":"need https proxy? 1 == true","required":false,"value":[1]},"region":{"desc":"Get Region Proxy","required":false,"value":"region name like \u4e2d\u56fd or \u5e7f\u5dde or \u6c5f\u82cf"},"type":{"desc":"clear proxy 1 or (common) anonymous 2","required":false,"value":[1,2]}},"desc":"Get All Proxy"},"/v1/proxies/stat/":{"args":{},"desc":"Statistics All Vaild Proxies"},"/v1/proxy/":{"args":{"https":{"desc":"need https proxy? 1 == true","required":false,"value":[1]},"region":{"desc":"Get Region Proxy","required":false,"value":"region name like \u4e2d\u56fd or \u5e7f\u5dde or \u6c5f\u82cf"},"token":{"desc":"Avoid Get Repetition Proxy","required":false,"value":"random string + random number"},"type":{"desc":"clear proxy 1 or (common) anonymous 2","required":false,"value":[1,2]}},"desc":"Get A Random Proxy"}}}]

**Comment by ozhiwei** [comment]
抱歉, 上面写了调用的API.

`http://yourdomain.com/api/v1/proxy/`
