### ISSUE TITLE
建议增加手动移除proxy机制

### ISSUE THREAD

**Issue by jasonlee529** [1again/ProxyPool#21]
连接池中的ip在爬虫是失败后，连接池是没有失败信息的，失败IP无法移除。
建议增加手动移除IP方法。

**Comment by ozhiwei** [comment]
有个参数`hold_useful_proxy_number`这个参数能够控制保留可用代理的数量.
这个参数是这么考虑, 

我们不知道究竟失败多少次的代理应该被丢弃
但我们可以知道我们需要多少个可用代理

**Comment by jasonlee529** [comment]
hold_useful_proxy_number 控制的是pool自检的参数吧。
场景是这样子的：当使用方通过一个代理去爬取页面，如果爬取成功了，代理有效；如果代理访问失败了，使用方可以手动移除这个代理，保证后续的爬取不再使用此代理。

**Comment by ozhiwei** [comment]
每个代理有个分数, 代理访问失败会扣分.
达到一定分数之后就不会再使用了.

这样设计主要是考虑, 代理访问失败一次不能确定这个代理是无法使用的.
可能是网络波动, 或者自身网络的问题, 或者是代理的调整.

**Comment by jasonlee529** [comment]
代理是否可用的决定权可以放给使用方，或者有办法让使用方反馈代理的分数。
当使用方发现某个代理不好用时，使用方无法做出任何的反馈。只有等待pool的自身调度评分。

**Comment by ozhiwei** [comment]
你说的有道理.
当时设计的时候希望使用者不需要关注代理的问题, 专注在爬虫的逻辑上.

当代理访问出错时, 下次使用动态代理请求就不会使用了.
并且延长了代理的检测时间, 直到某次代理检测确认这个异常的代理可用为止

**Comment by jasonlee529** [comment]
有计划最近做吗？

**Comment by ozhiwei** [comment]
这个已经实现了啊, 使用动态代理时, 只会获取上次检测成功的代理

**Comment by ozhiwei** [comment]
你这个问题可能是另一个情况.
检测的站点可以正常使用, 但是爬虫的站点无法正常使用.

**Comment by jasonlee529** [comment]
quality 标识质量吗？

**Comment by jasonlee529** [comment]
嗯。增加了一个api方法，通过代理爬取失败时，将quality置为-1。
