### ISSUE TITLE
MongoDB 是一个好的选择吗？

### ISSUE THREAD

**Issue by kslr** [1again/ProxyPool#6]
- 总体数量在10～20万条
- qps没有特殊要求
- 数据库维护成本
- 运行环境要求 ( 内存等)

这些数据包含了IPV4，IPV6(?) 加上巡查信息，非常简单，是否可以保存在内存(文件)中呢？
ipv 4字节 * 20个整数 * 100万  只需要几十兆内存

**Comment by ozhiwei** [comment]
你说的没错, 但我觉得吧, 
目前大多数内存数据库都是kv类型的
而kv类型的数据库不方便使用数据

举个例子, 我要过滤所有的中国proxy.

内存数据库我需要把所有数据查出来.
然后在过滤出所有的中国proxy.

而在mongodb里面, 我只需要一条查询语句就可以了.
我们的目标是灵活, 所以会有大量这种情况出现.
用kv存储在开发时会很麻烦.
而用RDBMS又觉得有点多余
毕竟没那么高的事务要求和对数据的关系依赖.

所以目前就我所所知的数据库mysql, redis, mongodb来说
mongodb可能是比较适合的吧!
