### ISSUE TITLE
代码结构需要优化哦

### ISSUE THREAD

**Issue by somewheve** [1again/ProxyPool#7]
粗浅看了下  你是用java模式来写python?  这个结构有点那个了  。。

**Comment by ozhiwei** [comment]
哪个?
1. 然而我并不会写java.
2. 项目是从[jhao104/proxy_pool](https://github.com/jhao104/proxy_pool)fork出来的, 已经在之前的结构上做了些优化, 但我的模式设计水平确实还有待提高.
3. 项目做下来我也不太满意, 所以在思考如何迭代.
4. 友善的提醒, 你这个提问的方式也有待改进.

以上
