### ISSUE TITLE
大神，能细说说如何使用嘛 比如在scrapy中

### ISSUE THREAD

**Issue by Ingram7** [1again/ProxyPool#8]

**Comment by ozhiwei** [comment]
别叫大神. 心慌.
[scrapy使用proxy参考这里](https://www.cnblogs.com/v-BigdoG-v/p/7443623.html)
使用动态代理参考README.

另外, 别做伸手党, 对你没好处.

**Comment by Ingram7** [comment]
Thanks♪(･ω･)ﾉ
