### ISSUE TITLE
can't open file 'Src/Run/main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by singee77** [1again/ProxyPool#9]
#### 开发环境部署
1. `$ docker volume create --name mogodata`
2. `$ docker run -d --name mongo -v mongodata:/data -p 27017:27017 mongo`
    `7cf7aa8d406386e6555529f3960a82c3ce364f311510e3cccaa2dbf2f5a49b7f`
4. `docker run -it --rm --link mongo:proxy_pool_db -v /e/python/ProxyPool/:/usr/src/app -p 35050:35050 1again/proxy_pool`
 `*python: can't open file 'Src/Run/main.py': [Errno 2] No such file or directory*`

**Comment by ozhiwei** [comment]
1. 建议使用linux环境.
2. 使用win10 docker 需要在右下角的小鲸鱼图标上开启对e盘的共享. 具体你可以自行查找一下操作.

**Comment by singee77** [comment]
开启了挂载，不知道是不是windows的问题，还是用linux算了

**Comment by ozhiwei** [comment]
![图片](https://user-images.githubusercontent.com/2688145/59552148-bc267400-8fb5-11e9-9de6-054cbf6d4ead.png)

你这里共享了吗?

win10的docker本质上还是用virtualbox虚拟的linux实现的docker

你可以直接进linux看下win10的目录有没映射进去.

**Comment by singee77** [comment]
感谢提醒，确实是目录没有映射进去的问题。

之前确认是映射起的，只是后面开了vpn就断开了，在stackoverflow搜索之后确认在windows上确实存在这个问题。

程序已经跑起来了。
